### ISSUE TITLE
[Question] Chromium binary in layer

### ISSUE THREAD

**Issue by fire015** [Sparticuz/chromium#155]
Is the Chromium binary already decompressed when used as a layer?

I see the check for `/tmp/chromium` in the code but I don't quite follow the logic around publishing chromium-v116.0.0-layer.zip because when I unzip this file manually I see `chromium.br` which suggests it would still be compressed in the layer.

Also according to AWS docs a layer is extracted into `/opt` so I am totally confused as to how this package would pick this up from the layer.

**Comment by fire015** [comment]
Having done some further tests inside Lambda my conclusion is no... it will still have to deflate even as a layer. Any possibility of changing that? Still not clear what the /tmp check is for.

**Comment by Sparticuz** [comment]
It's compressed because the layer was too big to be used otherwise. Though I just took a look at lambda's docs and I can't find what the layer size limit is, they may have dropped it? I'll need to look into it.

The /tmp/chromium check is to see if the binary has already been extracted, it will skip if it's already there. If it's not a cold start, it should be there already.

**Comment by fire015** [comment]
I just tried to upload a zip of the extracted binaries as a layer and I got the error "The selected file is too large. The maximum size is 50.0 MB."

Guess this isn't possible, shame!

**Comment by KuraiAndras** [comment]
@fire015 Upload the layer from s3. It seems that the 50mb limit is only for direct upload zip files
