### ISSUE TITLE
Error: Cannot find module '@sparticuz/chromium

### ISSUE THREAD

**Issue by gulshansainis** [Sparticuz/chromium#4]
I followed the instruction to create layer and attach it to the lambda function however I am still getting following error.

```
Test Event Name
event

Response
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '@sparticuz/chromium'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module '@sparticuz/chromium'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:951:17)",
    "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)",
    "    at async start (file:///var/runtime/index.mjs:1137:23)",
    "    at async file:///var/runtime/index.mjs:1143:1"
  ]
}

Function Logs
Unknown application error occurred
Runtime.ImportModuleError
2022-10-08T07:11:45.439Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@sparticuz/chromium'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module '@sparticuz/chromium'","Require stack:","- /var/task/index.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}
2022-10-08T07:13:35.744Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@sparticuz/chromium'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module '@sparticuz/chromium'","Require stack:","- /var/task/index.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}
START RequestId: 688c27ef-4936-4ebb-b55b-4f03edaad219 Version: $LATEST
END RequestId: 688c27ef-4936-4ebb-b55b-4f03edaad219
REPORT RequestId: 688c27ef-4936-4ebb-b55b-4f03edaad219	Duration: 1426.51 ms	Billed Duration: 1427 ms	Memory Size: 128 MB	Max Memory Used: 12 MB	
Unknown application error occurred
Runtime.ImportModuleError

Request ID
688c27ef-4936-4ebb-b55b-4f03edaad219
```

<img width="1275" alt="Screenshot 2022-10-08 at 12 55 02 PM" src="https://user-images.githubusercontent.com/8197984/194695525-43b816e2-5644-4c3e-8dbd-9b8a94d5c402.png">

**Comment by Sparticuz** [comment]
Can you look at the layer and show me what it looks like, or post the zip?

**Comment by gulshansainis** [comment]
Since file size is more than 25MB limit sharing link for same
https://www.transfernow.net/dl/20221008TdSJ3dRD

**Comment by Sparticuz** [comment]
It looks like somehow you're layer got an extra zip inside of it. (Left is mine, right is yours, I downloaded right from the Lambda layers page on AWS)
![image](https://user-images.githubusercontent.com/161913/194894477-e84d6a59-8faf-4afa-9430-815b38025c71.png)

You just want to upload the `chromium.zip` and it should just have the `nodejs` folder inside of it. I'm not sure how the chromium.zip file got added to another zip file. Did you download a Github CI Build artifact, or follow [this](https://github.com/Sparticuz/chromium#aws-lambda-layer)?

**Comment by oantyneskul** [comment]
I had the same issue. Moving the package from dev-dependencies to dependencies inside package.json resolved it.

**Comment by gulshansainis** [comment]
@Sparticuz 
To fix this issue, I manually copied the `node_modules` folder under `nodejs` folder and the zip it.
I will give it try again using the CI Build artifacts once I get time.

@oantyneskul 
I verified package.json and everything is under dependencies section
```
{
  "dependencies": {
    "@sparticuz/chromium": "^107.0.0",
    "axios": "^1.1.2",
    "playwright-core": "^1.27.0",
    "puppeteer-core": "^18.1.0"
  }
}
```

**Comment by EdWilsonOrigo** [comment]
> You just want to upload the `chromium.zip` and it should just have the `nodejs` folder inside of it. I'm not sure how the chromium.zip file got added to another zip file. Did you download a Github CI Build artifact, or follow [this](https://github.com/Sparticuz/chromium#aws-lambda-layer)?

I followed the new section which linked to the CI runs. The artefact I download from https://github.com/Sparticuz/chromium/actions/runs/3191558127 is the one that includes an extra chromium.zip

After correcting the zip, I'm still getting an error in AWS

`2022-10-16T22:01:08.190Z	xxxxxxxxxxxxxxxx	ERROR	[Error: ENOENT: no such file or directory, open '/var/bin/chromium.br'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/bin/chromium.br'
}`

I'm deploying via terraform rather than your aws cli commands, but I'm pretty sure its all connected up correctly. I'm not sure if its related to the final comment in #1? but the path I'm getting is different to the one in his error.

**Comment by MuppetPower** [comment]
> You just want to upload the `chromium.zip` and it should just have the `nodejs` folder inside of it. I'm not sure how the chromium.zip file got added to another zip file. Did you download a Github CI Build artifact, or follow [this](https://github.com/Sparticuz/chromium#aws-lambda-layer)?

I followed the new section which linked to the CI runs. The artefact I download from https://github.com/Sparticuz/chromium/actions/runs/3191558127 is the one that includes an extra chromium.zip

After correcting the zip, I'm still getting an error in AWS

`2022-10-16T22:01:08.190Z	xxxxxxxxxxxxxxxx	ERROR	[Error: ENOENT: no such file or directory, open '/var/bin/chromium.br'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/bin/chromium.br'
}`

I'm deploying via terraform rather than your aws cli commands, but I'm pretty sure its all connected up correctly. I'm not sure if its related to the final comment in #1? but the path I'm getting is different to the one in his error.

**Comment by Sparticuz** [comment]
> I followed the new section which linked to the CI runs. The artefact I download from [Sparticuz/chromium/actions/runs/3191558127](https://github.com/Sparticuz/chromium/actions/runs/3191558127) is the one that includes an extra chromium.zip

Ah, ok. It looks like github is adding an extra zip layer. I wonder if they just zip up all artifacts. The correct file to use as the lambda layer is the `chromium.zip` INSIDE of the github artifact. I will make a note about this.

Also, yes, changing to a regular production dependency will work just fine because then you are packaging the binaries directly with your code, but many of us run into deployment limits because it's over 50 megs.

**Comment by Gonzalo8642** [comment]
> > I followed the new section which linked to the CI runs. The artefact I download from [Sparticuz/chromium/actions/runs/3191558127](https://github.com/Sparticuz/chromium/actions/runs/3191558127) is the one that includes an extra chromium.zip
> 
> Ah, ok. It looks like github is adding an extra zip layer. I wonder if they just zip up all artifacts. The correct file to use as the lambda layer is the `chromium.zip` INSIDE of the github artifact. I will make a note about this.
> 
> Also, yes, changing to a regular production dependency will work just fine because then you are packaging the binaries directly with your code, but many of us run into deployment limits because it's over 50 megs.

I'm on a mac and it unzipped both of them, which is why it took me a while to stumble into this issue.
For a split second I can see both of them expanding
<img width="365" alt="image" src="https://user-images.githubusercontent.com/16733681/199849912-182ba610-4428-47ac-9228-d92ae0a96c93.png">

If I go to the terminal and use `unzip chromium.zip -d temp` it will only unzip the first one.

**Comment by GeniusWiki** [comment]
After many tries, I successfully run a sample code (create PDF from URL) in AWS Lambda.  I am not a JS developers so I am not 100% understand the process yet, I will do more tries to confirm my process.  Here I just list what I did for now that may be helpful if you got trouble at lambda deployment:

* Whatever I use CI (gitlab) or run my local, it seems double  zipped.  It is pretty hard to figure out if you are using Mac as it will automatically unzip twice. Try  @Gonzalo8642 tip: `unzip chromium.zip -d temp` to confirm your zip is correct.
* If I directly deployed the zip from default `make` as lambda layer (after fix double zip), I got two issues:
1. the  puppeteer-core cannot be found
2.  It reports `Cannot find module '/opt/nodejs/node_modules/@sparticuz/chromium/build/index.js'`

To fix these issues, I commented this line in make file
`# npx clean-modules --directory nodejs --include "**/*.d.ts" "**/@types/**" "**/*.@(yaml|yml)" --yes`

I also run `npm install puppeteer-core` in a separated empty folder,  then copy this project node_modules to overwrite(you cannot install puppeteer-core in current nodejs folder as it will overwrite some files in this projects node_modules)

The final layer zip is about 60M. 

* The last thing worth to note,  Lambda nodejs must be > 14.x.

**Comment by BrianHung** [comment]
> I'm on a mac and it unzipped both of them, which is why it took me a while to stumble into this issue. For a split second I can see both of them expanding <img alt="image" width="365" src="https://user-images.githubusercontent.com/16733681/199849912-182ba610-4428-47ac-9228-d92ae0a96c93.png">
> 
> If I go to the terminal and use `unzip chromium.zip -d temp` it will only unzip the first one.

Use `zipinfo chromium.zip` to check if the zip downloaded from Github actions contains a nested chromium.zip or whether it contains a nodejs.

**If it contains a nested zip, AWS lambda layer will not extract this!**

**Comment by Sparticuz** [comment]
I'm going to close this issue as it's easily solved by following these instructions.

https://github.com/Sparticuz/chromium#aws-lambda-layer
