### ISSUE TITLE
[BUG] Error when using @vercel/ncc

### ISSUE THREAD

**Issue by rdmchr** [Sparticuz/chromium#5]
## Environment
* `chromium` Version: 107.0.0
* `puppeteer-core` Version:19.1.1
* Node.js Version: 16.x
* Lambda / GCF Runtime: public.ecr.aws/lambda/nodejs:16

## Expected Behavior

The browser should launch correctly.

## Current Behavior

The function crashes with the following error:
```
2022-10-25T08:02:50.440Z	d7c6474c-48a1-495e-b094-58711bb1a7a9	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "ENOENT: no such file or directory, open '/var/bin/chromium.br'",
    "code": "ENOENT",
    "errno": -2,
    "syscall": "open",
    "path": "/var/bin/chromium.br",
    "stack": [
        "Error: ENOENT: no such file or directory, open '/var/bin/chromium.br'"
    ]
}
```

## Steps to Reproduce

I built a minimal project that showcases the bug: https://github.com/rdmchr/pkg-chromium-test
Just clone the project, build it locally and push it to ECR.
After that you can create Lambda where you select that container.

## Possible Solution

I'm not quite sure this is even a problem with this library. Maybe a way to generate the Chromium file which could then be copied from the builder part to the actual part of the Dockerfile would be useful.

**Comment by Sparticuz** [comment]
If you are using a dockerfile, I would think it would be a better all around solution to just put chromium in the container, and not even use this package. It would be less code because then you are just using puppeteer, and also you'd save a few milliseconds on extract at runtime.

Very loose psuedocode:
In the builder, install `brotli` and `wget/curl` (if needed, not sure what node:16-buster has in it), then get the .br files in my repo and extract them, doesn't matter where. `brotli --decompress` and `tar xf swiftshader.tar/aws.tar`. Then, in the actual container, do a COPY and put `chromium` in `/usr/bin` (or somewhere in $PATH). Then put the `lib` of aws.tar.br in `/usr/lib`. Swiftshader, i'm not 100% sure where they would go, I would try `/usr/lib` first, then if that didn't work, try a subfolder of `swiftshader` where you put the `chromium` binary (`/usr/bin/swiftshader` probably wrong, but should work). After doing that, puppeteer should just see chromium in $PATH and it should 'just work'.

**Comment by Sparticuz** [comment]
Regardless, a great feature would be to specify the location of the brotli files, whether it's a local file, or a remote file. (S3). I don't know how @vercel/vcc works, but it looks like it's specifying the wrong location of the file.

**Comment by rdmchr** [comment]
Yeah, that seems like a nice feature. I got my set-up working thanks to your pointers! So if this is no longer needed you can feel free to close this issue.
