### ISSUE TITLE
[BUG] chromium.executablePath yields null (version 108)

### ISSUE THREAD

**Issue by jamesjjk** [Sparticuz/chromium#6]
## Environment
* `chromium` Version: @sparticuz/chromium@108
* `puppeteer` / `puppeteer-core` Version: "puppeteer-core": "19.2.0"
* Node.js Version: 14

## Expected Behavior

Should yield a path

## Current Behavior

chromium.executablePath yields null (version 108)

**Comment by lubuzzo** [comment]
I had the same issue running locally, I solved adding the

`NODE_ENV = "test"`

In my .env.

Also, I needed to install dotenv and use it in my script:

`require('dotenv').config();`

**Comment by Sparticuz** [comment]
It returns `null` when when [this function](https://github.com/Sparticuz/chromium/blob/7b58b551cf15640cec73701c3796e747ad8734f1/source/index.ts#L215) returns `false`, It's a holdover from `chrome-aws-lambda`, I'm not sure if it should still be there.

**Comment by lubuzzo** [comment]
IMO, it should not be there.

In the context of aws-lambda make some sense, because it need to check if the code is running in the Lambda/GCP CF, but I guess this abstraction of chromium is more generic.

**Comment by Sparticuz** [comment]
I think I agree with you. In fact, I added the node_env=test case because I was getting nulls also during my CI testing, which isn't done on Lambda.

If I can't think of any reason to keep it, I'll remove it next week and release an update

**Comment by paulstelzer** [comment]
@Sparticuz any idea when you will release it?

**Comment by lubuzzo** [comment]
@Sparticuz I took the liberty to do a PR to solve this question: #11 

Instead of change [this function](https://github.com/Sparticuz/chromium/blob/7b58b551cf15640cec73701c3796e747ad8734f1/source/index.ts#L215), I've changed [this one](https://github.com/Sparticuz/chromium/blob/7b58b551cf15640cec73701c3796e747ad8734f1/source/index.ts#L182), because there are a couple of examples of use of Puppeteer/Playwright that will use the return of the first function (even on the readme of your repository) - so, I guess this is a best approach than remove the `headless` function

**Comment by Sparticuz** [comment]
108.0.1 released with this fix
